import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import App from "./App";

import "./_index.scss";

const geistSans = Geist({
  weight: ["400", "500"],
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  weight: ["400", "500"],
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className={geistSans.className}>
        <App>{children}</App>
      </body>
    </html>
  );
}